# AutoApply.AI Configuration

# Resume Configuration
resume:
  path: "data/resumes/resume.pdf"
  cache_dir: "data/cache"
  update_interval: 86400

# Email Configuration
email:
  enabled: true
  from_name: "Felipe França Nogueira"
  from_email: "felipefrancanogueira@gmail.com"
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  smtp_username: "felipefrancanogueira@gmail.com"
  smtp_password: "your-app-specific-password"  # Replace with your Gmail App Password
  signature_path: "templates/email_signature.txt"

# LinkedIn Configuration
linkedin:
  enabled: true
  email: "your-linkedin-email"  # Replace with your LinkedIn email
  password: "your-linkedin-password"  # Replace with your LinkedIn password
  feed_search:
    max_posts: 100
    days_back: 7
    scroll_delay: 2
    keywords:
      - "software engineer"
      - "developer"
      - "full stack"
      - "backend"
      - "frontend"
      - "react"
      - "node.js"
      - "python"
  job_search:
    locations:
      - "Worldwide"
      - "Remote"
      - "United States"
      - "Canada"
      - "Europe"
    experience_levels:
      - "Entry Level"
      - "Associate"
      - "Mid-Senior Level"
      - "Senior"
    job_types:
      - "Full-time"
      - "Contract"
      - "Remote"

# Storage Configuration
storage:
  applications_db: "data/applications.db"
  cover_letters_dir: "data/cover_letters"
  attachments_dir: "data/attachments"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/autoapply.log"
  max_size: 10485760
  backup_count: 5

# Job Search Configuration
job_search:
  platforms:
    - linkedin_feed
    - linkedin_jobs
    - hackernews
    - github_jobs
  required_skills:
    - javascript
    - react
    - node.js
  preferred_skills:
    - typescript
    - python
    - aws
  min_salary: 100000  # USD per year
  remote_only: true
  locations:
    - "Remote"
    - "Worldwide"
    - "United States"
    - "Canada"
  excluded_terms:
    - "senior staff"
    - "principal"
    - "director"
    - "manager"
