# AutoApply.AI Configuration

# Resume Configuration
resume:
  path: "data/resume.pdf"  # Path to your resume PDF
  cache_dir: "data/cache"  # Directory to cache parsed resume data
  update_interval: 86400   # How often to re-parse resume (in seconds)

# Job Search Configuration
job_search:
  platforms:
    linkedin:
      enabled: true
      search_interval: 3600  # How often to search (in seconds)
      keywords: []  # Additional keywords to include in search
      locations: []  # Preferred locations
      remote_only: true
      
    indeed:
      enabled: true
      search_interval: 3600
      keywords: []
      locations: []
      remote_only: true
      
    remotive:
      enabled: true
      search_interval: 3600
      keywords: []
      
    weworkremotely:
      enabled: true
      search_interval: 3600
      keywords: []
      
    greenhouse:
      enabled: true
      search_interval: 3600
      keywords: []

  # Job matching configuration
  matching:
    min_score: 0.5  # Minimum match score (0-1)
    required_skills: []  # Skills that must be present
    preferred_skills: []  # Skills that are preferred but not required
    excluded_keywords: []  # Keywords to exclude from matches
    max_applications_per_day: 50

# Application Configuration
application:
  cover_letter:
    enabled: true
    template: "templates/cover_letter.txt"
    customize: true  # Whether to customize for each job
    
  email:
    enabled: true
    from_name: ""  # Your full name
    from_email: ""  # Your email address
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    smtp_username: ""  # Your email username
    smtp_password: ""  # Your app-specific password
    signature: "templates/email_signature.txt"

# OAuth Configuration
oauth:
  linkedin:
    client_id: ""
    client_secret: ""
    redirect_uri: ""
    
  indeed:
    client_id: ""
    client_secret: ""
    redirect_uri: ""

# API Configuration
api:
  groq:
    api_key: ""  # Groq API key for cover letter generation
    model: "mixtral-8x7b-32768"  # Model to use
    
# Logging Configuration
logging:
  level: "INFO"
  file: "logs/autoapply.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Storage Configuration
storage:
  applications_db: "data/applications.db"  # SQLite database for tracking applications
  cover_letters_dir: "data/cover_letters"  # Directory to store generated cover letters
  attachments_dir: "data/attachments"      # Directory for resume and other attachments
  resumes_dir: "data/resumes"             # Directory for storing resumes
  cache_dir: "data/cache"                 # Directory for caching
  jobs_dir: "data/jobs"                   # Directory for job data
  raw_jobs_dir: "data/jobs/raw"          # Directory for raw job listings
  processed_jobs_dir: "data/jobs/processed" # Directory for processed job listings 