# LinkedIn Credentials
linkedin:
  email: "test@gmail.com"
  password: "ABCDED"
  enabled: true

# Email Configuration
email:
  username: "test@gmail.com"
  password: "ABCDED"
  sendgrid_api_key: "SENDGRID_API_KEY"
  sendgrid_from_email: "test@gmail.com"
  sendgrid_from_name: "Test User"

# Search Configuration
search:
  max_applications_per_day: 50
  max_jobs_per_platform: 100
  search_delay: 2
  remote_only: true
  application_delay: 5
  max_concurrent_applications: 10

# Primary Skills for Job Matching
skills:
  - "software engineer"
  - "developer"
  - "python"
  - "react"
  - "node.js"
  - "full stack"
  - "backend"
  - "frontend"
